# Generated by Django 5.1 on 2025-09-27 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiffinVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(help_text='Name of the kitchen/tiffin service', max_length=200)),
                ('address', models.TextField(help_text='Complete address of the kitchen')),
                ('phone_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text="Indicates if the vendor's profile is live")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiffin Vendor',
                'verbose_name_plural': 'Tiffin Vendors',
                'db_table': 'vendors_tiffin_vendor',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dish', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the dish')),
                ('image', models.ImageField(blank=True, help_text='Image of the dish', null=True, upload_to='menu_items/')),
                ('category', models.CharField(choices=[('main_course', 'Main Course'), ('side_dish', 'Side Dish'), ('bread', 'Bread'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('snack', 'Snack')], default='main_course', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item', max_digits=8)),
                ('is_vegetarian', models.BooleanField(default=True, help_text='Is this item vegetarian?')),
                ('is_vegan', models.BooleanField(default=False, help_text='Is this item vegan?')),
                ('is_spicy', models.BooleanField(default=False, help_text='Is this item spicy?')),
                ('preparation_time', models.PositiveIntegerField(default=30, help_text='Preparation time in minutes')),
                ('is_available', models.BooleanField(default=True, help_text='Is this item currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='vendors.tiffinvendor')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'name'],
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the menu (e.g., 'Monday Special', 'Weekend Feast')", max_length=200)),
                ('date', models.DateField(help_text='Date for which this menu is created')),
                ('is_active', models.BooleanField(default=True, help_text='Is this menu currently active?')),
                ('special_instructions', models.TextField(blank=True, help_text='Any special instructions for this menu', null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price for complete menu', max_digits=10, null=True)),
                ('max_orders', models.PositiveIntegerField(default=50, help_text='Maximum number of orders for this menu')),
                ('orders_count', models.PositiveIntegerField(default=0, help_text='Current number of orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_items', models.ManyToManyField(help_text='Items included in this menu', related_name='daily_menus', to='vendors.menuitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='vendors.tiffinvendor')),
            ],
            options={
                'verbose_name': 'Daily Menu',
                'verbose_name_plural': 'Daily Menus',
                'ordering': ['-date', 'name'],
                'unique_together': {('vendor', 'date', 'name')},
            },
        ),
    ]
