# Generated by Django 5.1 on 2025-09-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'Daily Dabba Menu', 'verbose_name_plural': 'Daily Dabba Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Items'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='max_orders',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='orders_count',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='special_instructions',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='menu',
            name='cooking_style',
            field=models.CharField(blank=True, default='', help_text="Cooking style (e.g., 'Punjabi Style', 'Gujarati Thali', 'South Indian')", max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='dabbas_sold',
            field=models.PositiveIntegerField(default=0, help_text='Number of dabbas already sold'),
        ),
        migrations.AddField(
            model_name='menu',
            name='extras',
            field=models.ManyToManyField(blank=True, help_text='Extra items (sweet, drink)', limit_choices_to={'category__in': ['sweet', 'drink']}, related_name='extra_menus', to='vendors.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='full_dabba_price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Total price for complete dabba', max_digits=8),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, help_text="Photo of today's prepared dabba", null=True, upload_to='dabba_images/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_veg_only',
            field=models.BooleanField(default=True, help_text='Is this a pure veg dabba?'),
        ),
        migrations.AddField(
            model_name='menu',
            name='main_items',
            field=models.ManyToManyField(blank=True, help_text='Main items (roti, sabzi, dal, rice, non-veg)', limit_choices_to={'category__in': ['roti_bread', 'sabzi', 'dal', 'rice_item', 'non_veg']}, related_name='main_menus', to='vendors.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='max_dabbas',
            field=models.PositiveIntegerField(default=30, help_text='Maximum number of dabbas you can prepare'),
        ),
        migrations.AddField(
            model_name='menu',
            name='side_items',
            field=models.ManyToManyField(blank=True, help_text='Side items (pickle, papad, raita, salad)', limit_choices_to={'category__in': ['pickle_papad', 'raita_salad']}, related_name='side_menus', to='vendors.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='todays_special',
            field=models.CharField(blank=True, default='', help_text="What's special about today's dabba?", max_length=300),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available_today',
            field=models.BooleanField(default=True, help_text="Available for today's dabba?"),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(help_text='Date for which this dabba menu is created'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default="Today's Special", help_text="Name of today's menu (e.g., 'Monday Special', 'Non-Veg Combo')", max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='vendors.tiffinvendor'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('roti_bread', 'Roti/Bread'), ('sabzi', 'Sabzi (Vegetable)'), ('dal', 'Dal'), ('rice_item', 'Rice Item (Biryani/Pulao)'), ('non_veg', 'Non-Veg (Chicken/Mutton/Fish)'), ('pickle_papad', 'Pickle/Papad'), ('sweet', 'Sweet/Dessert'), ('drink', 'Drink/Lassi'), ('raita_salad', 'Raita/Salad')], default='sabzi', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=True, help_text='Veg or Non-veg?'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Name of the dish (e.g., Aloo Sabzi, Chicken Curry)', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per portion/serving', max_digits=6),
        ),
    ]
